### ISSUE TITLE
NullPointerException on analyzeAccount(..)

### ISSUE THREAD

**Issue by marcodomenicano** [fxjordan/botometer-java#1]
Hi, 
i'm using your libraries but i get an error during execution. In particular it gives NullPointerException in:

Exception in thread "main" java.lang.NullPointerException
	at java.util.Locale.<init>(Locale.java:648)
	at java.util.Locale.<init>(Locale.java:701)
	at de.fjobilabs.botometer.twitterclient.twitter4j.Twitter4JUser.getLang(Twitter4JUser.java:137)
	at de.fjobilabs.twitter.dto.UserDTO.<init>(UserDTO.java:115)
	at de.fjobilabs.twitter.dto.TweetDTO.<init>(TweetDTO.java:115)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.fjobilabs.botometer.client.AbstractBotometerClient.checkAccount(AbstractBotometerClient.java:72)
	at de.fjobilabs.botometer.AccountAnalyzingBotometer.analyzeAccountData(AccountAnalyzingBotometer.java:83)
	at de.fjobilabs.botometer.AccountAnalyzingBotometer.analyzeAccount(AccountAnalyzingBotometer.java:72)

**Comment by fxjordan** [comment]
Hi thanks for reporting the error.

The 'lang' property of a user returned by Twitter4J can be null. The Twitter4JUser.getLang() method should return null in that case.

I'll fix this later today!

**Comment by fxjordan** [comment]
@marcodomenicano The problem should be fixed in v0.1.1. Could you verify this?

**Comment by marcodomenicano** [comment]
Hi Felix,
I will check this evening! Thank you for your rapid Fix!

Il giorno mer 22 mag 2019 alle 17:41 Felix Jordan <notifications@github.com>
ha scritto:
